'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Containers

    '''<summary>
    '''ribbonContainers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ribbonContainers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNew As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtDelete As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbSysInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSysInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divEntryContainers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEntryContainers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbContainer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbMawb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMawb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbHawb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHawb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCustomerID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbCustomerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCustomerInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDeliveredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDeliveredDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbLastUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLastUpdated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ribbonContainersDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ribbonContainersDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtClearSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtClearSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtDeleteList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtDeleteList As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''divDatagrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDatagrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''cbDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDetail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbContainerSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbContainerSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbHawbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHawbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbMawbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMawbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCustomerSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCustomerSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddStatusSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStatusSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbReceivedDateSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceivedDateSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDeliveredDateSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDeliveredDateSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbUserSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUserSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLastUpdatedSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastUpdatedSearch As Global.System.Web.UI.WebControls.TextBox
End Class
