'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class masterMain

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''divHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHead As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtLogoAgility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtLogoAgility As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbUsernameTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUsernameTop As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtUserTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtUserTop As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtHome As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''divSideNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSideNav As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtMenu As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtUserLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtUserLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbUsernameLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUsernameLeft As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtMaster As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tblSubmenuMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSubmenuMaster As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbDummy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDummy1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLocation As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDummy2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDummy2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCustomer As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtContainerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtContainerList As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbContainer As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtInspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtInspection As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbInspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbInspection As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtTemperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtTemperature As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbTemperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTemperature As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtPod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtPod As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbPod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPod As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtSetting As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSetting As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tblSubmenuSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSubmenuSetting As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUser As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRole As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtReport As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtHelp As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbHelp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ibtLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtLogout As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPlaceHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cphContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
