'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProofOfDelivery

    '''<summary>
    '''divRibbonDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRibbonDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtClearSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtClearSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtDeleteList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtDeleteList As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtExport As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''divDatagrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDatagrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''cbDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDetail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbIdSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbIdSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddHandoverTypeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddHandoverTypeSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbReceivedSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceivedSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDepartmentSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDepartmentSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbRemarkSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRemarkSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbHawbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHawbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbContainerNumberSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbContainerNumberSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbUserSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUserSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLastUpdatedSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastUpdatedSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddPictureSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPictureSearch As Global.System.Web.UI.WebControls.DropDownList
End Class
